version: "3.8"

services:
  db:
    image: mongo:4.0-xenial
    ports:
      - 27017:27017
    volumes:
      - vidly:/data/db

  api:
    build: ./backend
    ports:
      - 3001:3001
    environment:
      DB_URL: mongodb://db/vidly
    volumes:
      - ./backend:/app
    command: ./docker-entrypoint.sh

  web:
    build: ./frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app

# Service for running tests
  web_tests:
    image: dockerized-fullstack-app_web
    volumes:
      - ./frontend:/app
    command: npm test
    
# We have to define our volume before we can use it
volumes:
  vidly:
    